name: 'Frontend CI'

on:
  push:
    paths:
      - 'starting_point/frontend/**'
  pull_request:
    paths:
      - 'starting_point/frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starting_point/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './starting_point/frontend/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  storybook-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starting_point/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # Ensure consistency across jobs
          cache: 'npm'
          cache-dependency-path: './starting_point/frontend/package-lock.json'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm ci
      - name: Rebuild native modules
        run: npm rebuild
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook --quiet
      - name: Run Storybook tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook"